name: Maven Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Build with Maven
        working-directory: Project files
        run: mvn -B package --file pom.xml -X -Dspring.profiles.active=test

      - name: List target directory (debug step)
        working-directory: Project files
        run: ls -l target

      - name: Publish to GitHub Packages Apache Maven
        working-directory: Project files
        run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml -Dspring.profiles.active=test
        env:
          GITHUB_TOKEN: ${{ github.token }}
