name: Maven Package

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}

      # FIX: Apply the working-directory to the specific path within the checked-out repository
      - name: Build with Maven
        # This assumes your pom.xml is inside a folder named 'Banking-system' at the root of your GitHub repository.
        # So, the path becomes: /home/runner/work/YOUR_REPO_NAME/YOUR_REPO_NAME/Banking-system
        working-directory: Banking-system
        run: mvn -B package --file pom.xml

      - name: Publish to GitHub Packages Apache Maven
        # Apply the same working-directory here
        working-directory: Banking-system
        run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
        env:
          GITHUB_TOKEN: ${{ github.token }}
