name: Maven Package

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Build with Maven
        # FIX: Set the working directory to 'Project files'
        working-directory: Project files
        run: mvn -B package --file pom.xml -X -Dspring.profiles.active=test # Added -Dspring.profiles.active=test
        
      - name: Publish to GitHub Packages Apache Maven
        # FIX: Apply the same working directory here
        working-directory: Project files
        run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
        env:
          GITHUB_TOKEN: ${{ github.token }}
