# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Essential permission to write to GitHub Packages

    steps:
      - uses: actions/checkout@v4 # Checks out your repository code

      - name: Set up JDK 23 # UPDATED: Changed from JDK 11 to JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23' # UPDATED: This now matches your pom.xml's java.version
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml (which is 'github')
          settings-path: ${{ github.workspace }} # Location for the settings.xml file

      - name: Build with Maven
        run: mvn -B package --file pom.xml # Builds your Spring Boot application (creates the JAR)

      - name: Publish to GitHub Packages Apache Maven
        run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml # Deploys the built JAR to GitHub Packages
        env:
          GITHUB_TOKEN: ${{ github.token }} # Automatically provided token with 'packages: write' permission
